version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "develop"
    directory: "/"
    reviewers:
      - "justedlev"
    assignees:
      - "justedlev"
    labels:
      - "status: review"
      - "lang: java"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    reviewers:
      - "justedlev"
    assignees:
      - "justedlev"
    labels:
      - "status: review"
      - "area: ci/cd"
    schedule:
      interval: "weekly"
