name: Sonatype Workflow

on:
  release:
    types: [ published ]
    tags: [ "v*.*.*" ]
  workflow_dispatch:

jobs:
  publish:
    name: Sign and Publish to Sonatype
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Maven settings.xml
        id: maven-settings
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: |
            [
              {
                "id": "central",
                "username": "${env.SONATYPE_USERNAME}",
                "password": "${env.SONATYPE_PASSWORD}"
              }
            ]
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Set up GPG for signing
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import --no-tty --yes
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: List GPG keys
        run: gpg --list-keys

      - name: Prepare mvnw
        run: chmod +x ./mvnw

      - name: Publish to Sonatype Central
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          ./mvnw -B clean deploy -P release \
            -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE
